// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtN9RNxq9qf8phwxHrw46Ux8-O__yzEE0',
    appId: '1:215930717754:web:526c4f3abf72a6e9159703',
    messagingSenderId: '215930717754',
    projectId: 'autocar-5fd51',
    authDomain: 'autocar-5fd51.firebaseapp.com',
    storageBucket: 'autocar-5fd51.firebasestorage.app',
    measurementId: 'G-6D70598BEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUETbWc9Z01kj60st-fC4W_a_P5Z48j40',
    appId: '1:215930717754:android:73d62804e72eb3dc159703',
    messagingSenderId: '215930717754',
    projectId: 'autocar-5fd51',
    storageBucket: 'autocar-5fd51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADq5DGzBvoYKnD16UzO6HGY0v6-EIZDL4',
    appId: '1:215930717754:ios:74bbe372ec92fa2a159703',
    messagingSenderId: '215930717754',
    projectId: 'autocar-5fd51',
    storageBucket: 'autocar-5fd51.firebasestorage.app',
    iosBundleId: 'com.example.carManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADq5DGzBvoYKnD16UzO6HGY0v6-EIZDL4',
    appId: '1:215930717754:ios:74bbe372ec92fa2a159703',
    messagingSenderId: '215930717754',
    projectId: 'autocar-5fd51',
    storageBucket: 'autocar-5fd51.firebasestorage.app',
    iosBundleId: 'com.example.carManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtN9RNxq9qf8phwxHrw46Ux8-O__yzEE0',
    appId: '1:215930717754:web:794e212bcbdcba05159703',
    messagingSenderId: '215930717754',
    projectId: 'autocar-5fd51',
    authDomain: 'autocar-5fd51.firebaseapp.com',
    storageBucket: 'autocar-5fd51.firebasestorage.app',
    measurementId: 'G-RS0NVF65XE',
  );
}
